# Rent Details
URL = 'https://cleartax.in/save/rent'
MONTHLY_RENT = 12345
HOUSE_ADDRESS = 'YOUR HOUSE ADDRESS'
NAME = 'YOUR NAME'
EMAIL = 'YOUR EMAIL'
OWNER = 'LANDLORD NAME'
DATE_FORMAT = '%d/%m/%Y'
DOWNLOAD_DIR = 'PATH TO DOWNLOAD FOLDER'
